[package]
name = "pico"
version = "0.1.0"
edition = "2021"
author = "Sylvia Waldron"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24"
clap = { version = "4.1", features = ["derive"] }